### ISSUE TITLE
Ridicously complex for an example.

### ISSUE THREAD

**Issue by SkybuckFlying** [nvpro-samples/gl_cuda_interop_pingpong_st#2]
No project file for visual studio.

And massive ammounts of additional libraries/includes/directories/headers required.

Try make a 1000x shorter example.

This is how far I got with empty visual studio 2010 project:

WTF is chrono ? Windows Explorer can't find it.(And I am not even on Windows 10, funny joke)

1>------ Build started: Project: Test1, Configuration: Debug Win32 ------
1>Build started 1/2/2020 0:29:08.
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
1>InitializeBuildStatus:
1>  Touching "Debug\Test1.unsuccessfulbuild".
1>ClCompile:
1>  visualizeGL.cpp
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2589: '(' : illegal token on right side of '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2059: syntax error : '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(215): error C2864: 'NVPWindow::m_internal' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(296): error C2864: 'NVPWindow::m_isFullScreen' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(297): error C2864: 'NVPWindow::m_isClosing' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\profiler.hpp(39): fatal error C1083: Cannot open include file: 'chrono': No such file or directory
1>  ui.cpp
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2589: '(' : illegal token on right side of '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2059: syntax error : '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(215): error C2864: 'NVPWindow::m_internal' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(296): error C2864: 'NVPWindow::m_isFullScreen' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(297): error C2864: 'NVPWindow::m_isClosing' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\profiler.hpp(39): fatal error C1083: Cannot open include file: 'chrono': No such file or directory
1>  simulationInit.cpp
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2589: '(' : illegal token on right side of '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2059: syntax error : '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(215): error C2864: 'NVPWindow::m_internal' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(296): error C2864: 'NVPWindow::m_isFullScreen' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(297): error C2864: 'NVPWindow::m_isClosing' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\profiler.hpp(39): fatal error C1083: Cannot open include file: 'chrono': No such file or directory
1>  simulateCUDA.cpp
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2589: '(' : illegal token on right side of '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2059: syntax error : '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(215): error C2864: 'NVPWindow::m_internal' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(296): error C2864: 'NVPWindow::m_isFullScreen' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(297): error C2864: 'NVPWindow::m_isClosing' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\profiler.hpp(39): fatal error C1083: Cannot open include file: 'chrono': No such file or directory
1>  gl_cu_interop_pingpong_st.cpp
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2589: '(' : illegal token on right side of '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\cameracontrol.hpp(149): error C2059: syntax error : '::'
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(215): error C2864: 'NVPWindow::m_internal' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(296): error C2864: 'NVPWindow::m_isFullScreen' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvpwindow.hpp(297): error C2864: 'NVPWindow::m_isClosing' : only static const integral data members can be initialized within a class
1>x:\cuda c\tests\test opengl interop\original\gl_cuda_interop_pingpong_st\shared_sources\nvh\profiler.hpp(39): fatal error C1083: Cannot open include file: 'chrono': No such file or directory
1>  Generating Code...
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:12.73
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by NeilBickford-NV** [comment]
Hi SkybuckFlying,

`<chrono>` is the standard C++ date and time utility library, introduced in C++11 (see https://en.cppreference.com/w/cpp/chrono for an example including usage of `<chrono>`). Since it was introduced in C++11, is it possible that Visual Studio 2010 might not know about it (since the 2010 version only had partial support for 2011's C++11, see https://stackoverflow.com/questions/18615439/visual-studio-2010-chrono-header-file-missing)? (From https://github.com/nvpro-samples/build_all, we're primarily using Visual Studio 2017 internally, and some people on the team are moving to Visual Studio 2019.)

The nvpro-samples shared_sources library can be pretty large! Most of the time, you won't need to delve deeply into it to figure out how the application does what it does. In this case, if you're implementing GL/CUDA interoperability, all the code you'll need can be found in the README at https://github.com/nvpro-samples/gl_cuda_interop_pingpong_st/blob/master/README.md and (more deeply) https://github.com/nvpro-samples/gl_cuda_interop_pingpong_st/blob/master/simulateCUDA.cpp.

**Comment by NeilBickford-NV** [comment]
Updated the nvpro-samples README to specify C++14 in [commit db7aae84](https://github.com/nvpro-samples/build_all/commit/db7aae84853f0ce528cb209263c73fd77da3ccfd).
